language: java
cache:
directories:
- $HOME/.m2
jdk:
- oraclejdk8
script:
- mvn clean package

sudo: required
services:
- docker
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package docker:build
- docker build -t olmanstnathan/da2:test1
- docker push olmanstnathan/da2:test1